import { API_BASE_URL } from "../config/api";
import { useEffect, useState } from "react";
import {
  MapContainer,
  TileLayer,
  Marker,
  Popup,
} from "react-leaflet";
import L from "leaflet";
import "leaflet/dist/leaflet.css";

// ===============================
// Custom Vessel Icon
// ===============================

const vesselIcon = L.divIcon({
  className: "",
  html: `
    <div style="
      width: 38px;
      height: 38px;
      background: rgba(15, 23, 42, 0.95);
      border: 2px solid #38bdf8;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      box-shadow: 0 0 18px rgba(56,189,248,0.7);
      font-size: 20px;
    ">
      🚢
    </div>
  `,
  iconSize: [38, 38],
  iconAnchor: [19, 19],
  popupAnchor: [0, -20],
});

// ===============================
// Main Component
// ===============================

function VesselTracking() {
  const [vessels, setVessels] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  // ===============================
  // Fetch vessels
  // ===============================

  const fetchVessels = async () => {
    try {
      setError("");

      const response = await fetch(
        "${API_BASE_URL}/api/vessels/tracking"
      );

      const result = await response.json();

      console.log("VESSEL TRACKING RESPONSE:", result);

      if (!response.ok) {
        throw new Error(
          result.detail || "Failed to fetch vessel tracking data"
        );
      }

      setVessels(result.data || []);
    } catch (err) {
      console.error("Vessel tracking error:", err);

      setError(
        err.message || "Unable to load vessel tracking data"
      );

      setVessels([]);
    } finally {
      setLoading(false);
    }
  };

  // ===============================
  // Initial fetch + auto refresh
  // ===============================

  useEffect(() => {
    fetchVessels();

    const interval = setInterval(() => {
      fetchVessels();
    }, 30000);

    return () => clearInterval(interval);
  }, []);

  // ===============================
  // Loading
  // ===============================

  if (loading) {
    return (
      <div className="min-h-screen p-6 text-white bg-slate-950">
        <h1 className="text-3xl font-bold">
          Vessel Tracking
        </h1>

        <p className="mt-2 text-slate-400">
          Loading vessel positions...
        </p>
      </div>
    );
  }

  return (
    <div className="min-h-screen p-6 text-white bg-slate-950">

      {/* HEADER */}

      <div className="flex items-center justify-between mb-6">

        <div>
          <h1 className="text-3xl font-bold">
            Vessel Tracking
          </h1>

          <p className="mt-1 text-slate-400">
            Live vessel position monitoring and maritime route visibility
          </p>
        </div>

        <div className="flex items-center gap-2">

          <span className="w-3 h-3 bg-green-500 rounded-full animate-pulse" />

          <span className="text-sm text-green-400">
            Tracking Active
          </span>

        </div>

      </div>

      {/* SIMULATION NOTICE */}

      <div className="p-4 mb-6 border bg-blue-500/10 border-blue-500/30 rounded-xl">

        <div className="flex items-center justify-between gap-4">

          <div>

            <p className="font-medium text-blue-300">
              🛰️ Simulation Mode
            </p>

            <p className="mt-1 text-sm text-blue-400/70">
              Vessel coordinates are currently generated by the
              SAYLIV backend. Real AIS integration can replace
              this data source later.
            </p>

          </div>

          <button
            onClick={fetchVessels}
            className="px-4 py-2 text-blue-300 transition border rounded-lg bg-blue-500/20 border-blue-500/30 hover:bg-blue-500/30"
          >
            Refresh
          </button>

        </div>

      </div>

      {/* ERROR */}

      {error && (
        <div className="p-4 mb-6 text-red-300 border bg-red-500/10 border-red-500/30 rounded-xl">
          {error}
        </div>
      )}

      {/* MAP */}

      <div className="mb-6 overflow-hidden border bg-slate-900 border-slate-800 rounded-2xl">

        <div className="h-[550px]">

          <MapContainer
            center={[10, 75]}
            zoom={3}
            scrollWheelZoom={true}
            className="w-full h-full"
          >

            <TileLayer
              attribution="&copy; OpenStreetMap contributors"
              url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            />

            {/* VESSELS */}

            {vessels.map((vessel) => {

              if (!vessel.position) {
                return null;
              }

              const position = [
                vessel.position.latitude,
                vessel.position.longitude,
              ];

              return (
                <Marker
                  key={vessel.vessel_id}
                  position={position}
                  icon={vesselIcon}
                >

                  <Popup>

                    <div className="text-slate-900 min-w-[220px]">

                      <h3 className="text-lg font-bold">
                        🚢 {vessel.name}
                      </h3>

                      <p className="text-sm text-slate-500">
                        {vessel.vessel_id}
                      </p>

                      <div className="pt-3 mt-3 space-y-2 border-t">

                        <p>
                          <strong>Type:</strong>{" "}
                          {vessel.vessel_type}
                        </p>

                        <p>
                          <strong>Speed:</strong>{" "}
                          {vessel.speed_knots} kn
                        </p>

                        <p>
                          <strong>Heading:</strong>{" "}
                          {vessel.heading}°
                        </p>

                        <p>
                          <strong>Destination:</strong>{" "}
                          {vessel.destination}
                        </p>

                        <p>
                          <strong>ETA:</strong>{" "}
                          {vessel.eta
                            ? new Date(
                                vessel.eta
                              ).toLocaleString()
                            : "N/A"}
                        </p>

                        <p>
                          <strong>Position:</strong>{" "}
                          {vessel.position.latitude.toFixed(2)},
                          {" "}
                          {vessel.position.longitude.toFixed(2)}
                        </p>

                      </div>

                      <div className="mt-3">

                        <span className="inline-block px-3 py-1 text-xs text-green-700 bg-green-100 rounded-full">
                          {vessel.status}
                        </span>

                      </div>

                    </div>

                  </Popup>

                </Marker>
              );
            })}

          </MapContainer>

        </div>

      </div>

      {/* STATS */}

      <div className="grid grid-cols-1 gap-4 mb-6 md:grid-cols-4">

        <div className="p-5 border bg-slate-900 border-slate-800 rounded-xl">

          <p className="text-sm text-slate-400">
            Tracked Vessels
          </p>

          <p className="mt-2 text-3xl font-bold">
            {vessels.length}
          </p>

        </div>

        <div className="p-5 border bg-slate-900 border-slate-800 rounded-xl">

          <p className="text-sm text-slate-400">
            Available
          </p>

          <p className="mt-2 text-3xl font-bold text-green-400">
            {
              vessels.filter(
                (v) => v.status === "AVAILABLE"
              ).length
            }
          </p>

        </div>

        <div className="p-5 border bg-slate-900 border-slate-800 rounded-xl">

          <p className="text-sm text-slate-400">
            Destinations
          </p>

          <p className="mt-2 text-3xl font-bold text-blue-400">
            {
              new Set(
                vessels.map((v) => v.destination)
              ).size
            }
          </p>

        </div>

        <div className="p-5 border bg-slate-900 border-slate-800 rounded-xl">

          <p className="text-sm text-slate-400">
            Data Source
          </p>

          <p className="mt-2 text-lg font-semibold">
            Simulated AIS
          </p>

        </div>

      </div>

      {/* TABLE */}

      <div className="overflow-hidden border bg-slate-900 border-slate-800 rounded-2xl">

        <div className="p-5 border-b border-slate-800">

          <h2 className="text-lg font-semibold">
            Vessel Fleet
          </h2>

          <p className="mt-1 text-sm text-slate-400">
            Detailed vessel tracking information
          </p>

        </div>

        <div className="overflow-x-auto">

          <table className="w-full text-sm">

            <thead className="bg-slate-950 text-slate-400">

              <tr>

                <th className="p-4 text-left">
                  Vessel
                </th>

                <th className="p-4 text-left">
                  Position
                </th>

                <th className="p-4 text-left">
                  Speed
                </th>

                <th className="p-4 text-left">
                  Heading
                </th>

                <th className="p-4 text-left">
                  Destination
                </th>

                <th className="p-4 text-left">
                  ETA
                </th>

                <th className="p-4 text-left">
                  Status
                </th>

              </tr>

            </thead>

            <tbody>

              {vessels.map((vessel) => (

                <tr
                  key={vessel.vessel_id}
                  className="transition border-t border-slate-800 hover:bg-slate-800/50"
                >

                  <td className="p-4">

                    <div className="font-medium">
                      🚢 {vessel.name}
                    </div>

                    <div className="text-xs text-slate-500">
                      {vessel.vessel_id}
                    </div>

                  </td>

                  <td className="p-4 text-slate-300">

                    {vessel.position
                      ? `${vessel.position.latitude.toFixed(
                          2
                        )} , ${vessel.position.longitude.toFixed(2)}`
                      : "N/A"}

                  </td>

                  <td className="p-4 text-blue-400">
                    {vessel.speed_knots} kn
                  </td>

                  <td className="p-4">
                    {vessel.heading}°
                  </td>

                  <td className="p-4">
                    {vessel.destination}
                  </td>

                  <td className="p-4 text-slate-300">

                    {vessel.eta
                      ? new Date(
                          vessel.eta
                        ).toLocaleString()
                      : "N/A"}

                  </td>

                  <td className="p-4">

                    <span className="px-3 py-1 text-xs text-green-400 border rounded-full bg-green-500/10 border-green-500/20">
                      {vessel.status}
                    </span>

                  </td>

                </tr>

              ))}

              {!error && vessels.length === 0 && (

                <tr>

                  <td
                    colSpan="7"
                    className="p-10 text-center text-slate-500"
                  >
                    No vessel tracking data available.
                  </td>

                </tr>

              )}

            </tbody>

          </table>

        </div>

      </div>

    </div>
  );
}

export default VesselTracking;